# TODO require puppet-lint
language: ruby
rvm: 
 - 1.8.7
 - 1.9.3
branches:
  only:
    - master
notifications:
  email:
    - palladius@github.com
    - palladiusbonton@gmail.com
#env:
#  - PUPPET_VERSION=2.6.14
#  - PUPPET_VERSION=2.7.11
